puts "The Sudents of Villans Acadmey"
puts "-----------------"
puts "Dr. Hannible Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "michael Corleone"
puts "Alex Delarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
